### ISSUE TITLE
Make the app get Downloads from GitHub releases 

### ISSUE THREAD

**Issue by JohnBetaro** [Iamlooker/Droid-ify#334] opened 2023-04-26 10:34 UTC
Hi, is there anyway that maybe in the future you can make Droid-ify pull apps directly from GitHub releases like [Obtainium](https://github.com/ImranR98/Obtainium) does ? I'm not saying ditching F-Droid, just the option to add GitHub releases like adding any other F-Droid repository, because there are some really cool apps we can only get from GitHub and it's pain to update them regularly.

**Comment by Iamlooker** [comment] 2023-05-02 18:29
Duplicate of #18

**Closed by Iamlooker** 2023-05-02 18:29 UTC
Labels: enhancement
