### ISSUE TITLE
[Bug] Adding a Repo crashes the app when syncing / Crash on corrupt index file

### ISSUE THREAD

**Issue by Mindirix** [Iamlooker/Droid-ify#77] opened 2022-08-19 12:48 UTC
I am trying to add a repo :

Molly non foss repo: https://molly.im/fdroid/repo

after adding it when i click the sync button it processes all the repos fine and crashes the app when it gets to the final repo which is the added one.

i am using Droid-ify V 0.4.7

**Comment by Iamlooker** [comment] 2022-08-30 06:50
Is this fixed in v0.4.8?

**Comment by Mindirix** [comment] 2022-08-30 11:14
Just tested it, its working now but another problem appeared now the app crashes if i enable f-droid archive repo and click sync

disabling f-droid archivr repo solves it but i do need it.

let me know if i should open a separate issue.

thanks.

**Comment by Iamlooker** [comment] 2022-08-30 12:02
The issue seems to be caused by a corrupt/wrong index file been pushed from F-Droid's side, all I can do is to make it show a notification but I cannot fix the index file.

Hopefully they will fix the issue with next push.

I will rename this issue to `Crash on corrupt index file` and close it once I fix it :)

**Closed** 2022-08-30 12:08 UTC

**Comment by Iamlooker** [comment] 2022-08-30 12:43
This should be fixed in this release

**Comment by Mindirix** [comment] 2022-08-31 08:33
The app doesn't crash any more it shows via notification :

Could not parse the index file for f-droid archive.

**Comment by Iamlooker** [comment] 2022-08-31 08:55
Cool

**Comment by EdoSecco** [comment] 2023-02-27 14:06
> I'm not sure if it's due to my phone (let's say, it has Android 8, ect.) but the app shows again the problem: when it catches a repo with errors, it crashes instead of showing a simple error message "repo not found" or "sync error". Example: https://gsantner.gitlab.io/fdroid/repo I have the version 0.5.5 via F-Droid repo

Still trying after a week, still same problem. @Iamlooker will you reopen this issue?
