### ISSUE TITLE
mass app updates stopped working in 0.5.7 (legacy mode). 

### ISSUE THREAD

**Issue by Wjxfi** [Iamlooker/Droid-ify#303] opened 2023-03-17 20:39 UTC
something happens in the notifications, but there is no android dialog "download?".
The session installer works perfectly.
miui, android 12

**Comment by Iamlooker** [comment] 2023-03-18 06:26
Why create two issues?

Duplicate of #286

**Closed by Iamlooker** 2023-03-18 06:26 UTC
