### ISSUE TITLE
download gets stuck

### ISSUE THREAD

**Issue by Tanzin01** [Iamlooker/Droid-ify#194] opened 2022-12-11 18:42 UTC
if file is larger than 100MB, download gets stuck. i have to click on "install" again for the download to resume

**Comment by vertigo220** [comment] 2022-12-11 19:19
This might be an issue with the app itself. Which one is it? The only one I can think of that I have that's >100MB is Bromite, but I don't have this problem with it. Also, your phone and Android version might be helpful.

**Comment by vertigo220** [comment] 2022-12-12 16:21
It may be your connection, too. Maybe it's unstable and disconnects, even briefly, during the download. The server for Bromite's repo is very slow, and downloading it takes a long time compared to others (not just because of its size, but the speed itself is much slower).

**Comment by vertigo220** [comment] 2022-12-12 22:51
I should clarify that if you can test this on a different connection to see if the issue is with your device or the connection, if it ends up being due to the connection, the dev may be able to improve Droid-ify's robustness with handling such issues. So closing the issue may be premature.

**Comment by Iamlooker** [comment] 2022-12-14 13:52
This might be an issue with bromite repo, though I am not sure either. I will be closing this issue for now.
You can re-open it anytime you feel like

**Closed by Iamlooker** 2022-12-14 13:52 UTC

**Comment by ShareASmile** [comment] 2022-12-14 16:16
> I will be closing this issue for now.
> You can re-open it anytime you feel like

No, a user can't reopen an issue/PR closed by owner/maintainers.

Let user close that so that he can reopen if he wants to..
OR advise to open a new issue if he faces issue again mentioning this issue

**Comment by Tanzin01** [comment] 2022-12-15 09:32
I tried with another connection just now.

after clicking the "install" button, about 10sec passed but i was still seeing the *connecting* with a "cancel" button below page. tapped the cancel, no changes of the page/ui, connecting with the cancel button below. So i quit the app, re-entered, tapped on the install button of bromite 

And  33+MB has already been downloaded. rest of the file downloaded without any issue.

So the bottom line is, the download was usual except at first "download progress" ui issue¿

**Comment by vertigo220** [comment] 2022-12-15 15:14
It sounds like possibly the same as #90 / #149, would you agree @Tanzin01?

**Comment by Tanzin01** [comment] 2022-12-15 18:29
um, somewhat aligned but not the same.

 in my case, its "downloading progress ui/animation issue" unlike others 2. which are install & update related. anyway, i dont think this ui/animeation is much of a deal as long as apps is downloading in the background.

Thanks for your(and everyone else's) time & effort behind this app.
