### ISSUE TITLE
Auto-updating apps after updating repos

### ISSUE THREAD

**Issue by soredake** [Iamlooker/Droid-ify#152] opened 2021-12-20 10:41 UTC
Would be nice to have such option.

**Comment by yephny** [comment] 2021-12-20 19:21
Duplicate of #3

**Comment by soredake** [comment] 2021-12-20 20:08
By updating i mean upgrading, instaling updates

**Comment by yephny** [comment] 2021-12-20 20:40
Oh, I thought they were trying to say auto installing updates in #3 but all that's been mentioned is auto downloading, you might be onto something.

**Comment by machiav3lli** [comment] 2022-01-18 00:18
Already solved in #159

**Closed** 2022-01-18 00:18 UTC
