### ISSUE TITLE
[Enhancement] Change the notification icon for new updates

### ISSUE THREAD

**Issue by shom13** [Iamlooker/Droid-ify#173] opened 2022-02-12 09:37 UTC
This is not an issue, but an enhancement request. The current notification icon for updates looks scary and intimadating, its more like a warning sign rather than a pleasant update notification. Could you change it if possible.

**Comment by machiav3lli** [comment] 2022-02-15 02:26
Duplicate of #101

**Closed by machiav3lli** 2022-02-15 02:26 UTC
