### ISSUE TITLE
Add swipe to refresh feature

### ISSUE THREAD

**Issue by abdalmoniem** [Iamlooker/Droid-ify#294] opened 2023-03-09 21:01 UTC
Instead of having a dedicated refresh button, it'd be nice to add a swipe to refresh button, and if the user has already scrolled down too far, they can tap on the currently active tab to scroll back up and refresh at the same time, or it could be a FAB that appears when the user has scrolled two or three items.

**Comment by Iamlooker** [comment] 2023-03-13 09:12
Duplicate of #215

**Closed by Iamlooker** 2023-03-13 09:12 UTC
Labels: enhancement
