### ISSUE TITLE
Animation causing motion sickness

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [Iamlooker/Droid-ify#228] opened 2023-02-03 16:03 UTC
The sliding animation when swiping between the "Explore" and "Installed" screens in the main list area give me motion sickness. The animation is uneven and jarring, I can't use the app because of it.

A floating icon in the bottom right corner would be more appropriate. Could this be considered?
https://m3.material.io/components/floating-action-button/specs#a700a701-dc98-4599-9394-087ee35191fc

**Comment by jcperil** [comment] 2023-02-06 16:26
I think the unevenness could be solved by #189, i.e. adding the filters (Automation, Connectivity, etc.) in all tabs - Explore, Installed, Updates.

Or moving the filter entirely to the top bar, next to Search, Sync buttons.

**Comment by Iamlooker** [comment] 2023-02-10 19:34
Duplicate of #102

**Closed by Iamlooker** 2023-02-10 19:34 UTC
Labels: enhancement
