### ISSUE TITLE
Downloads menu

### ISSUE THREAD

**Issue by ghost** [Iamlooker/Droid-ify#301] opened 2023-03-17 07:42 UTC
A downloads menu so when i download a bunch of apps i can install them.
I know i can install them from notifications but a downloads menu will be usefull

**Comment by theuserwhoisnotadeveloper** [comment] 2023-03-17 17:33
it can be integrated into updates tab the same way play store does.

**Comment by Iamlooker** [comment] 2023-04-13 08:09
Duplicate of #43

**Closed by Iamlooker** 2023-04-13 08:09 UTC
Labels: enhancement
