### ISSUE TITLE
[BUG] Update All Button Always Visible

### ISSUE THREAD

**Issue by abdalmoniem** [Iamlooker/Droid-ify#293] opened 2023-03-09 20:57 UTC
**Describe the bug**
The Update All Button is always visible even if there're no updates. Also, it is not visible on the screen until you scroll. It's not a big deal but an improvement nonetheless 

**To Reproduce**
1. Go to 'Updates'

**Expected behavior**
Update All Button is not visible and no scrolling

**Screenshots**
![Screenshot_20230308-210354_Droid-ify.png](https://user-images.githubusercontent.com/11904264/224156177-a597d5e2-6b4b-49ff-8005-1b3feea77b46.png)

![Screenshot_20230308-210349_Droid-ify.png](https://user-images.githubusercontent.com/11904264/224156227-d749dd4f-9179-458f-83aa-46a15be80f03.png)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: riceDroid 10.2 (Android 13)
 - Version [e.g. v0.5.6 (56)]

**Additional context**
N/A

**Comment by bt90** [comment] 2023-03-11 14:28
Duplicate of #265 ?

**Comment by abdalmoniem** [comment] 2023-03-12 15:51
well yes and no, there's the issue that it shows at all when there're no updates as well.

**Closed** 2023-03-13 10:30 UTC
Labels: bug
