### ISSUE TITLE
[Feature request]  possibilty to export the list of (custom added) repositories

### ISSUE THREAD

**Issue by vaginessa** [Iamlooker/Droid-ify#239] opened 2023-02-06 23:41 UTC
I use Droid-ify on a few devices.
Having lots of custom added repos in the list, its a pain to keep every device up to date/synced manually.

A possibilty to export/backup the list of (custom added) repositories would be great. (to .xml, .json, .html etc)

Such a function would make it much easier to:
- setup Droid-ify on new devices with your custom repos
- sync custom repos between different devices

🤔

**Comment by Iamlooker** [comment] 2023-02-08 19:18
Duplicate of #19

**Closed by Iamlooker** 2023-02-08 19:18 UTC
Labels: enhancement
