### ISSUE TITLE
[Feature Request] Loading modal when opening downloaded package

### ISSUE THREAD

**Issue by cyclonejet** [Iamlooker/Droid-ify#149] opened 2022-10-24 04:31 UTC
Whenever an application is downloaded, and pressed installed, it takes some time for the installation confirmation modal to show up. It would be very helpful if there was any indication that the downloaded package is being opened.

**Comment by Donkey-Doug** [comment] 2022-10-27 17:50
There is a notification, right?

**Comment by Iamlooker** [comment] 2022-10-28 04:53
> There is a notification, right?

Yes but I think he is saying, after clicking the notification it should show a loading state until the prompt is shown.

Yes this would be added, can't assure you when but yes.

**Comment by vertigo220** [comment] 2022-12-11 20:52
Related to/duplicate of #90

**Comment by Iamlooker** [comment] 2023-01-31 10:51
Merge with #90

**Closed by Iamlooker** 2023-01-31 10:51 UTC
