### ISSUE TITLE
[Feature request] Ability to export/import installed application list

### ISSUE THREAD

**Issue by Fehertukor** [Iamlooker/Droid-ify#181] opened 2022-11-27 00:21 UTC
Hello,

Thank you for your work!
I love it!
Please if you have time implement this feature!
Ability to export/import installed application list

**Comment by vertigo220** [comment] 2022-12-11 20:10
Duplicate of #145 which covers not only this but backup of settings/repos as well.

**Closed** 2022-12-16 06:34 UTC
Labels: duplicate
