### ISSUE TITLE
Enlarged screenshot not showing

### ISSUE THREAD

**Issue by haarp** [Iamlooker/Droid-ify#130] opened 2021-11-27 14:42 UTC
Sometimes, when tapping on a screenshot to show it, the view dims but no picture will be shown. When you swipe to the next screenshot, that one will be shown, but the first one will almost always be missing.

- App has 2 screenshots
- Tap first screenshot
- > Dim, nothing shown
- Swipe to next screenshot
- > Screenshot shown
- Swipe back
- > Still missing

If the same is started by tapping the second screenshot, it will be the one not being shown, while swiping to the first one works.

Thanks!

**Comment by machiav3lli** [comment] 2021-11-28 00:42
Duplicate of #104

**Closed by machiav3lli** 2021-11-28 00:42 UTC
