### ISSUE TITLE
System language use the wrong language

### ISSUE THREAD

**Issue by baptiste0928** [Iamlooker/Droid-ify#55] opened 2022-07-21 14:18 UTC
Hello ! I noticed that the "System" option in language settings does not use the right language. My phone is in French, but the app remains in English. Notifications are not affected and are displayed in French.

App version: 0.4.7 (from F-Droid repos)
Android version: 12 (latest GrapheneOS version running on a Pixel 5)

**Comment by GameOverFlowChart** [comment] 2022-07-22 12:32
Just checked, seems to be true, my app also uses English than I set it to system but my system language isn't English.

**Comment by Iamlooker** [comment] 2022-07-23 11:11
This has been fixed and will be released in next update.

Duplicate of #51

**Closed by Iamlooker** 2022-07-23 11:11 UTC
