### ISSUE TITLE
It is not possible to add two different repositories if their address starts the same

### ISSUE THREAD

**Issue by aykarpov** [Iamlooker/Droid-ify#57] opened 2022-07-23 14:02 UTC
The known repositories page https://forum.f-droid.org/t/known-repositories/721 has two different repositories "Molly" (https://molly.im/fdroid/repo/?fingerprint=3B7E93B1FE32C6E35A93D6DDFC5AFBEB1239A7C6EA6AF20FF33ED53CDC38B04A) and "Molly-FOSS" (https://molly.im/fdroid/foss/fdroid/repo/?fingerprint=5198DAEF37FC23C14D5EE32305B2AF45787BD7DF2034DE33AD302BDB3446DF74). You can only add one of them. When adding a second one, a message appears that such an address already exists.

**Comment by Iamlooker** [comment] 2022-07-23 18:17
Which version are you using? 
I can't reproduce this bug here on my device 😕

**Comment by Iamlooker** [comment] 2022-08-01 08:14
@aykarpov Can you please tell me which version of droidify are you using?

**Comment by revuwa** [comment] 2022-09-01 14:10
> I can't reproduce this bug here on my device

Me too. I could add both repos from above without any issues, (with v0.4.9).

**Comment by Iamlooker** [comment] 2022-09-02 03:07
> > I can't reproduce this bug here on my device
> 
> Me too. I could add both repos from above without any issues, (with v0.4.9).

So I will be closing the Issue

**Closed by Iamlooker** 2022-09-02 03:07 UTC
